dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: node_modules/api-mock/bin/api-mock apiary.apib --port 15432
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://localhost:15432'
